rotation:
  minRate: 60
  maxRate: 180

service:
  healthCheck:
    path: '/actuator/health'
    rate: 3 # rate at which, service instances health status is checked (in seconds)
  instances:
    -
      url: 'http://localhost:8080'
      os: 'debian-buster'
      configFileName: 'debian-buster.conf'
      containerName: 'service-buster'
    -
      url: 'http://localhost:8081'
      os: 'debian-bullseye'
      configFileName: 'debian-bullseye.conf'
      containerName: 'service-bullseye'
