rotation:
  minRate: 10
  maxRate: 20

service:
  healthCheck:
    path: '/actuator/health'
    rate: 3 # rate at which, service instances health status is checked (in seconds)
    port: 8080
  instances:
    -
      ip: '192.168.100.243'
      os: 'fedora'
    -
      ip: '192.168.100.244'
      os: 'windows'
    -
      ip: '192.168.100.249'
      os: 'ubuntu-server'

logging:
  level:
    spzc.*: DEBUG
