FROM gradle:7.4.2-jdk11-alpine
COPY --chown=gradle:gradle . /home/gradle/src
WORKDIR /home/gradle/src
RUN gradle build -x test --no-daemon; pwd; ls /home/gradle/src/build/libs/
# TODO uwspólnić ten pierwszy krok dla wszystkich dockerfajli
FROM openjdk:11-jdk-slim-bullseye

RUN mkdir /app

COPY --from=0 /home/gradle/src/build/libs/src.jar /app/app.jar

ENTRYPOINT ["java", "-jar", "-Dserver.port=8081", "/app/app.jar"]
# TODO ten port w entrypoincie też trzeba jakoś ograć envem